on:
  push:
    paths-ignore:
    - '**/.github/**'
    - '**README.md'
    branches:
      - main
  workflow_dispatch: 

jobs:
  release:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@6a8585e39eabcb53cdbdebfcc76eb9672199089e # v5.1.5
