on:
  push:
    paths-ignore:
    - '**/.github/**'
    - '**README.md'
    branches:
      - main
  workflow_dispatch: 

jobs:
  release:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@5f3998b2429f01ea86190e538e85ee3844c56f22 # v5.1.1
